import { COLORS } from "./colors";
import { StyleSheet } from "react-native";
import { Platform } from "react-native";

const styles = StyleSheet.create({
    safe: { flex: 1, backgroundColor: COLORS.peach },
    scroll: {
      paddingHorizontal: 22,
      paddingTop: 8,
      paddingBottom: 28,
      alignItems: "center",
      gap: 18,
    },
    headerRow: { width: "100%", alignItems: "flex-start", marginTop: 2 },
    backBtn: {
      borderWidth: 2,
      borderColor: COLORS.blueStroke,
      backgroundColor: "#F5EEDF",
      padding: 8,
      borderRadius: 12,
      shadowColor: COLORS.navy,
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
    title: {
      fontSize: 36,
      lineHeight: 40,
      color: COLORS.blueText,
      letterSpacing: 0.5,
      textAlign: "center",
    },
    iconPressable: {
      position: "relative",
      alignSelf: "center",
    },
    icon: {
      width: 88,
      height: 88,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: COLORS.navy, // palette border
      marginTop: 6,
      alignSelf: "center",
      // depth
      shadowColor: COLORS.teal,
      shadowOpacity: 0.25,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 4,
      backgroundColor: COLORS.cream,
    },
    editBadge: {
      position: "absolute",
      right: -6,
      bottom: -6,
      backgroundColor: COLORS.teal,
      borderRadius: 12,
      padding: 6,
      borderWidth: 2,
      borderColor: COLORS.cream,
    },
    formBlock: { width: "100%", marginTop: 8 },
    label: { color: COLORS.blueText, fontSize: 16, fontWeight: "700" },
    inputWrap: {
      marginTop: 8,
      borderWidth: 2,
      borderColor: COLORS.blueStroke,
      backgroundColor: COLORS.fieldBg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: Platform.select({ ios: 14, android: 6 }),
      shadowColor: COLORS.navy,
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
    withIcon: { position: "relative" },
    eyeBtn: {
      position: "absolute",
      right: 12,
      top: Platform.select({ ios: 14, android: 10 }),
      height: 28,
      width: 28,
      alignItems: "center",
      justifyContent: "center",
    },
    input: {
      fontSize: 18,
      color: COLORS.teal,
      paddingVertical: Platform.select({ ios: 4, android: 2 }),
    },
    error: { marginTop: 6, color: COLORS.error, fontSize: 13 },
    cta: {
      width: "100%",
      borderRadius: 18,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: COLORS.orange,
      shadowOpacity: 0.25,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      marginTop: 12,
    },
    ctaText: { color: "#FFFFFF", fontSize: 20, fontWeight: "800", letterSpacing: 0.25 },
    hint: { marginTop: 12, color: "rgba(107,84,76,0.85)", textAlign: "center" },
    link: { color: COLORS.teal, fontWeight: "700" },
 
  
    header: {
      paddingHorizontal: 16,
      paddingTop: 6,
      paddingBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: COLORS.cream,
    },
    headerBtn: {
      backgroundColor: COLORS.peach,
      padding: 10,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: COLORS.stroke,
      shadowColor: COLORS.navy,
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
    headerTitle: {
      fontSize: 28,
      color: COLORS.text,
      textAlign: "center",
      lineHeight: 28,
    },
  
    heroWrap: { marginBottom: 52 },
    banner: { height: 180, justifyContent: "flex-end" },
    bannerOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(3,64,64,0.35)",
    },
    avatarWrap: {
      position: "absolute",
      alignSelf: "center",
      bottom: -36,
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: "#fff",
      padding: 4,
      shadowColor: COLORS.navy,
      shadowOpacity: 0.25,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
    },
    avatar: { width: "100%", height: "100%", borderRadius: 48 },
    name: {
      position: "absolute",
      alignSelf: "center",
      bottom: -72,
      fontSize: 28,
      fontWeight: "800",
      color: COLORS.card,
      textShadowColor: "rgba(0,0,0,0.25)",
      textShadowRadius: 6,
      textShadowOffset: { width: 0, height: 2 },
    },
  
    cardStats: {
      marginTop: 54,
      marginHorizontal: 16,
      backgroundColor: COLORS.card,
      borderRadius: 16,
      paddingVertical: 16,
      paddingHorizontal: 12,
      flexDirection: "row",
      justifyContent: "space-around",
      borderWidth: 1,
      borderColor: COLORS.stroke,
      shadowColor: COLORS.navy,
      shadowOpacity: 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
    },
    statItem: { alignItems: "center", flex: 1 },
    statIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    statValue: { fontSize: 22, fontWeight: "800", color: COLORS.navy },
    statLabel: { marginTop: 2, fontSize: 12, color: "#8D7E74" },
  
    cardInfo: {
      marginTop: 16,
      marginHorizontal: 16,
      backgroundColor: COLORS.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.stroke,
      padding: 14,
      shadowColor: COLORS.navy,
      shadowOpacity: 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
    },
    infoRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10 },
    infoIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
      borderWidth: 1,
      borderColor: COLORS.stroke,
    },
    infoTitle: { color: COLORS.navy, fontWeight: "700", fontSize: 16 },
    infoSubtitle: { color: "#8D7E74", marginTop: 2 },
    divider: { height: 1, backgroundColor: COLORS.stroke, opacity: 0.6, marginHorizontal: 4 },
  
    sectionTitle: {
      marginTop: 18,
      marginHorizontal: 16,
      color: COLORS.text,
      fontWeight: "800",
      fontSize: 16,
    },
    cardAbout: {
      marginTop: 10,
      marginHorizontal: 16,
      backgroundColor: COLORS.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.stroke,
      padding: 16,
      shadowColor: COLORS.navy,
      shadowOpacity: 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
    },
    aboutText: { color: "#7A6A60", lineHeight: 20, fontSize: 14 },
  
    retryBtn: {
      backgroundColor: COLORS.teal,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
    },
  });





  export default styles;